//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuidFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT distinct
        ///	 tabs.name TableName
        ///	, &apos;[&apos;+c.name+&apos;]&apos; ColumnName
        ///FROM    
        ///	sys.columns c
        ///inner join
        ///	(select object_id, &apos;[&apos;+schema_name(schema_id)+&apos;].[&apos;+name+&apos;]&apos; name from sys.objects where type_desc = &apos;USER_TABLE&apos;) tabs on tabs.object_id = c.object_id
        ///INNER JOIN 
        ///	sys.types t ON c.user_type_id = t.user_type_id
        ///LEFT OUTER JOIN 
        ///	sys.index_columns ic ON ic.object_id = c.object_id AND ic.column_id = c.column_id
        ///WHERE
        ///	t.Name = &apos;uniqueidentifier&apos;
        ///order by
        ///	tabs.name,
        ///	&apos;[&apos;+c.name+&apos;]&apos;.
        /// </summary>
        internal static string ColumnsWithGuidsSql {
            get {
                return ResourceManager.GetString("ColumnsWithGuidsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 @ColumnName from @TableName where @ColumnName = @Guid.
        /// </summary>
        internal static string LookForGuidSql {
            get {
                return ResourceManager.GetString("LookForGuidSql", resourceCulture);
            }
        }
    }
}
